server:
  port: 9040

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.106.196.152:3306/mymall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5tRUDiyFRUXY7DAsEMDH
      secret-key: ehrYuAYOoME6kwdIx46hOeZPoRXknH
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com

  application:
    name: mymall-product

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:/mapper/**/*.xml


logging:
  level:
    com.cls.mymall.product.dao: debug